---
title: "Statistics Code"
author: "Megan"
date: "5/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Loading the the data for the analysis, Helminth data was turned into "1's" and "0's" if there is any worm detected or not

```{r}
Data <- read.csv("~/Desktop/Dissertation_data.csv", header = TRUE)
Data
```

Running basic description stats on a few of the columns of interest
```{r}
##TB1
sd(Data$TB1)
mean(Data$TB1)
min(Data$TB1)
max(Data$TB1)

##TB2                         
sd(Data$TB2)
mean(Data$TB2)
min(Data$TB2)
max(Data$TB2)

```


Running statistical tests on different parts of the dataset
```{r}
chisq.test(Data$interp, Data$Helminths) 

t.test(Data$TB1[Data$Helminths == 0], Data$TB1[Data$Helminths == 1])

t.test(Data$TB2[Data$Helminths == 0], Data$TB2[Data$Helminths == 1])

t.test(Data$TB1[Data$interp == 0], Data$TB1[Data$interp == 1])

t.test(Data$TB2[Data$interp == 0], Data$TB2[Data$interp == 1])


```

Making graphs from some of the data
```{r}
BMI_histo <- hist(Data$BMI, xlab = "Body Mass Index (BMI)",main = "Histogram of BMI's")

BMI_bar <- plot(Data$Sex, Data$BMI, ylab = "BMI", xlab = "Sex", main = "BMI Across Gender")

TB1_sex <- plot(Data$Sex, Data$TB1, ylab = "TB1", xlab = "Sex", main = "TB1 Results Across Gender")

TB2_sex <- plot(Data$Sex, Data$TB2, ylab = "TB2", xlab = "Sex", main = "TB2 Results Across Gender")

Interp_sex <- plot(Data$Sex, Data$interp, ylab = "Interpretation", xlab = "Sex", main = "Overall Results Across Gender")

MClan_TB1 <- plot(Data$Mother.s.Clan, Data$TB1, ylab = "TB1", xlab = "Mother's Clan", main = "Mother's Clan TB1 Results")

MClan_TB2 <- plot(Data$Mother.s.Clan, Data$TB2, ylab = "TB2", xlab = "Mother's Clan", main = "Mother's Clan TB2 Results")

FClan_TB1 <- plot(Data$Father.s.Clan, Data$TB1, ylab = "TB1", xlab = "Father's Clan", main = "Father's Clan TB1 Results")

FClan_TB2 <- plot(Data$Father.s.Clan, Data$TB1, ylab = "TB1", xlab = "Father's Clan", main = "Father's Clan TB1 Results")

```


