---
title: "Tests for the whole dataset"
author: "Megan"
date: "5/16/2020"
output: html_document
---

```{r setup}
## trying to make tables in publication style
Data <- read.csv("~/Desktop/Data.csv", header = TRUE)


library(expss)
library(tidyverse)

##selecting the columns we want to work with
new_data <- data.frame(Data$Sex, Data$DOB, Data$Helminths, Data$BMI, 
                       Data$Current.Residence, Data$Father.s.Clan, Data$Mother.s.Clan,
                       Data$Outcome) %>%
  rename(Sex = Data.Sex, Age = Data.DOB, Helminths = Data.Helminths, BMI = Data.BMI, 
         Location = Data.Current.Residence, "Father's Clan" = Data.Father.s.Clan,
         "Mother's Clan" = Data.Mother.s.Clan, Outcome = Data.Outcome)
new_data

##relabeling certain things
new_data = apply_labels(new_data,
                        Sex = "Sex",
                        Age = "Age",
                        Helminths = "Helminths",
                        Helminths = c("Detected" = 1, "Absent" = 0),
                        BMI = "BMI",
                        Location = "Current Residence",
                        "Father's Clan" = "Father's Clan",
                        "Mother's Clan" = "Mother's Clan",
                        Outcome = "Clinical Interpretation",
                        Outcome = c("Positive" = "POSITIVE", "Negative" = "NEGATIVE", 
                                    "Indeterminate"="INDETERMINATE"))

##table showing gender and outcome
cro(list(new_data$Sex, new_data$Age),new_data$Outcome)                    
##helminth and outcome
cro(new_data$Helminths,new_data$Outcome)   

## helminth and outcome across gender
cro_cpct(new_data$Sex, list(total(),new_data$Helminths, new_data$Outcome))

##messing around
new_data %>% 
  tab_cells(BMI, Age) %>%
  tab_cols(total(), Outcome, Helminths) %>% 
  tab_stat_mean_sd_n() %>%
  tab_pivot() %>% 
  set_caption("Table with summary statistics and significance marks.")

```

```{r}
H_data <- read.csv("~/Desktop/Helminth_data.csv", header = TRUE)

library(expss)
library(tidyverse)

##selecting the columns we want to work with just HELMINTH data
Hel_data <- data.frame(H_data$Sex, H_data$Age, H_data$H_species, H_data$Helminths, H_data$BMI, 
                       H_data$Current.Residence, H_data$Father.s.Clan, H_data$Mother.s.Clan,
                       H_data$interp) %>% 
  rename(Sex = H_data.Sex, Age = H_data.Age, "Helminth Species" = H_data.H_species, Helminths = H_data.Helminths, BMI = H_data.BMI, 
         Location = H_data.Current.Residence, "Father's Clan" = H_data.Father.s.Clan,
         "Mother's Clan" = H_data.Mother.s.Clan, Outcome = H_data.interp) %>%
  na.omit(Hel_data)

View(Hel_data)


Hel_data = apply_labels(Hel_data,
                        Sex = "Sex",
                        Age = "Age",
                        "Helminth Species" = "Helminth Species",
                        Helminths = "Helminths",
                        Helminths = c("Detected" = 1, "Absent" = 0),
                        BMI = "BMI",
                        Location = "Current Residence",
                        "Father's Clan" = "Father's Clan",
                        "Mother's Clan" = "Mother's Clan",
                        Outcome = "Clinical Interpretation",
                        Outcome = c("Positive" = "POSITIVE", "Negative" = "NEGATIVE", 
                                   "Positive*" = "POSITIVE*"))
##breaking it down by gender and outcome
cro(Hel_data$Sex,Hel_data$Outcome) 

##helminth infection and gender
cro(list(Hel_data$Sex, Hel_data$Age,Hel_data$Outcome), Hel_data$Helminths) 
```

